=== YeCH94/Lecture/Advanced Web Programming/XML Exercise/XML Exercise 1/bulletin.dtd
<!ELEMENT BOARD (NAME, ARTICLE+)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT ARTICLE (TITLE, MESSAGE, WRITER_ID, WRITER_NAME, REPLY*)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT REPLY (MESSAGE, WRITER_ID, WRITER_NAME)>
<!ELEMENT MESSAGE (#PCDATA)>
<!ELEMENT WRITER_ID (#PCDATA)>
<!ELEMENT WRITER_NAME (#PCDATA)>

=== YeCH94/Lecture/Advanced Web Programming/XML Exercise/XML Exercise 1/bulletin.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE BOARD SYSTEM "bulletin.dtd">
<BOARD>
    <NAME>Bulletin</NAME>
    <ARTICLE>
        <TITLE>Article</TITLE>
        <MESSAGE>This is article</MESSAGE>
        <WRITER_ID>201333471</WRITER_ID>
        <WRITER_NAME>Ye Chan-ho</WRITER_NAME>
        <REPLY>
            <MESSAGE>Reply 1</MESSAGE>
            <WRITER_ID>201300000</WRITER_ID>
            <WRITER_NAME>Hong Gil-dong</WRITER_NAME>
        </REPLY>
        <REPLY>
            <MESSAGE>Reply 2</MESSAGE>
            <WRITER_ID>201300000</WRITER_ID>
            <WRITER_NAME>Hong Gil-dong</WRITER_NAME>
        </REPLY>
    </ARTICLE>
</BOARD>
